/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["listSessions"];
        put?: never;
        /**
         * Create Session
         * @description 開廷する。続けて証拠品を用意する(`research` または `evidence`)。
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence-samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evidence Samples
         * @description 同梱の捜査結果の一覧。SearXNG なしで始めるときに使う。
         */
        get: operations["listEvidenceSamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/evidence/samples/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Use Evidence Sample
         * @description 同梱の捜査結果を証拠品として使う。`name` は一覧にあるものだけ受け付ける。
         */
        post: operations["useEvidenceSample"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description 役割ごとのモデル割り当て(api_key は返さない)。
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Research
         * @description 捜査をバックグラウンドで始める。進捗と結果は SSE で通知する。
         */
        post: operations["startResearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Evidence
         * @description 既存の捜査結果(`llm-court research` の JSON)を証拠品として使い、捜査を省略する。
         */
        put: operations["setEvidence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Session
         * @description 次の 1 手(発言または判決)をバックグラウンドで進める。発言は SSE でストリーミングする。
         */
        post: operations["advanceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Session
         * @description 判決まで自動で進める。
         */
        post: operations["runSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Choices
         * @description 人間の手番の選択肢。強さ(strong / weak / trap)は選ぶまで伏せる。
         */
        get: operations["getChoices"];
        put?: never;
        /**
         * Choose Option
         * @description 選択肢を選ぶ。代弁者が発言を清書し、次の人間の手番か判決まで進める。
         */
        post: operations["chooseOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description イベントログ(`after` より後の seq)。
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Session */
        get: operations["streamSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description 人間が読める Markdown の法廷記録。
         */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description 計測サマリ(ターンごとの待ち時間、トークン、構造化出力の失敗、出典の問題)。
         */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChoiceMade */
        ChoiceMade: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice_made";
            option: components["schemas"]["ChoiceOption"];
        };
        /** ChoiceOption */
        ChoiceOption: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "contradiction" | "probe" | "argument";
            /** Label */
            label: string;
            /** Pitch */
            pitch: string;
            contradiction?: components["schemas"]["ContradictionCandidate"] | null;
            /** Target Claim Id */
            target_claim_id?: string | null;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Source
             * @default analyst
             */
            source: ("analyst" | "rule") | null;
        };
        /**
         * ChoicesPrepared
         * @description 人間の手番に示す選択肢(分析官が生成)。
         */
        ChoicesPrepared: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choices_prepared";
            phase: components["schemas"]["DebatePhase"];
            /** Round */
            round: number;
            side: components["schemas"]["Side"];
            /** Options */
            options: components["schemas"]["ChoiceOption"][];
            /**
             * Discarded
             * @default 0
             */
            discarded: number;
        };
        /**
         * ChoicesView
         * @description 人間の手番で示されている選択肢(強さは伏せてある)。
         */
        ChoicesView: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["DebatePhase"];
            /** Round */
            round: number;
            side: components["schemas"]["Side"];
            /** Options */
            options: components["schemas"]["ChoiceOption"][];
            /** Penalty Gauge */
            penalty_gauge: number;
        };
        /** ChooseRequest */
        ChooseRequest: {
            /**
             * Option Id
             * @description 選ぶ選択肢の ID
             */
            option_id: string;
        };
        /**
         * CitationIssue
         * @description 発言中の出典の問題(存在しない証拠品、証拠品にない引用、出典なし)。
         */
        CitationIssue: {
            /** Statement Id */
            statement_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "unknown_evidence" | "unsupported_quote" | "no_citation";
            /** Evidence Id */
            evidence_id?: string | null;
            /** Detail */
            detail: string;
        };
        /** CitationIssuesDetected */
        CitationIssuesDetected: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "citation_issues_detected";
            /** Statement Id */
            statement_id: string;
            /** Issues */
            issues: components["schemas"]["CitationIssue"][];
        };
        /**
         * Claim
         * @description 発言から抽出した個々の主張。
         */
        Claim: {
            /** Id */
            id: string;
            /** Statement Id */
            statement_id: string;
            side: components["schemas"]["Side"];
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fact" | "value" | "inference";
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
        };
        /** ClaimsExtracted */
        ClaimsExtracted: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "claims_extracted";
            /** Statement Id */
            statement_id: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /**
         * ConfigView
         * @description 役割ごとのモデル割り当て(設定画面用。api_key は含めない)。
         */
        ConfigView: {
            /** Roles */
            roles: components["schemas"]["RoleAssignment"][];
        };
        /**
         * ContradictionCandidate
         * @description 矛盾候補。`evidence_id` と `other_claim_id` はどちらか(または両方なし)。
         */
        ContradictionCandidate: {
            /** Target Claim Id */
            target_claim_id: string;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Other Claim Id */
            other_claim_id?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "self_contradiction" | "evidence_conflict" | "logical_leap" | "definition_shift" | "fabricated_citation";
            /** Strength */
            strength: ("strong" | "weak" | "trap") | null;
            /** Rationale */
            rationale: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Topic
             * @description 論題
             */
            topic: string;
            /**
             * Rounds
             * @description 反論の往復数
             * @default 3
             */
            rounds: number;
            /** @description 人間が担当する陣営。省略すると LLM vs LLM */
            human_side?: components["schemas"]["Side"] | null;
        };
        /**
         * DebatePhase
         * @enum {string}
         */
        DebatePhase: "opening" | "rebuttal" | "closing" | "verdict";
        /** DebateSummary */
        DebateSummary: {
            /** Turns */
            turns: components["schemas"]["TurnMetrics"][];
            /** Llm Calls */
            llm_calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Llm Time Ms */
            llm_time_ms: number;
            /** Structured Calls */
            structured_calls: number;
            /** Structured Failures */
            structured_failures: number;
            /** Structured Retries */
            structured_retries: number;
            /** Citation Issues */
            citation_issues: {
                [key: string]: number;
            };
            /** Claims */
            claims: number;
            /** Wall Time S */
            wall_time_s: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Source Url */
            source_url: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Published Date */
            published_date?: string | null;
            /** Summary */
            summary: string;
            /** Key Facts */
            key_facts: components["schemas"]["KeyFact"][];
        };
        /** EvidenceCollected */
        EvidenceCollected: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "evidence_collected";
            report: components["schemas"]["ResearchReport"];
        };
        /**
         * EvidenceSample
         * @description 同梱の捜査結果(ブラウザから証拠品として選べる)。
         */
        EvidenceSample: {
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Evidence Count */
            evidence_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgeScore
         * @description 裁判長の 1 回の評価。
         */
        JudgeScore: {
            /** Order */
            order: components["schemas"]["Side"][];
            /** Scores */
            scores: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Rationale */
            rationale: string;
        };
        /** JudgeScored */
        JudgeScored: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "judge_scored";
            score: components["schemas"]["JudgeScore"];
        };
        /**
         * KeyFact
         * @description 証拠品から取り出した事実。`quote` は取得本文からの抜き書き。
         */
        KeyFact: {
            /** Text */
            text: string;
            /** Quote */
            quote: string;
            /** Quote Verified */
            quote_verified: boolean;
        };
        /**
         * LLMCallInfo
         * @description LLM 呼び出しの計測記録(`llm.metrics.LLMCallRecord` と同じ形)。
         *
         *     domain は他のパッケージに依存しないため、同じ形をここで定義する。
         */
        LLMCallInfo: {
            /** Call Id */
            call_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Role */
            role: string;
            /** Model Key */
            model_key: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "structured";
            /** Prompt Name */
            prompt_name?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Schema Name */
            schema_name?: string | null;
            /** Structured Mode */
            structured_mode?: string | null;
            /** Ttft Ms */
            ttft_ms?: number | null;
            /** Total Ms */
            total_ms: number;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Tokens Per S */
            tokens_per_s?: number | null;
            /** Success */
            success: boolean;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /** Error */
            error?: string | null;
            /** Messages */
            messages?: {
                [key: string]: string;
            }[] | null;
            /** Response Text */
            response_text?: string | null;
            /** Reasoning Text */
            reasoning_text?: string | null;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            } | null;
        };
        /** LLMCallRecorded */
        LLMCallRecorded: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "llm_call_recorded";
            call: components["schemas"]["LLMCallInfo"];
        };
        /**
         * NextTurn
         * @description 次に進む手番。
         */
        NextTurn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "statement" | "verdict";
            phase: components["schemas"]["DebatePhase"];
            /** Round */
            round: number;
            side?: components["schemas"]["Side"] | null;
            /**
             * By Human
             * @default false
             */
            by_human: boolean;
        };
        /** PenaltyApplied */
        PenaltyApplied: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "penalty_applied";
            /** Amount */
            amount: number;
            /** Remaining */
            remaining: number;
            /** Reason */
            reason: string;
        };
        /** PhaseStarted */
        PhaseStarted: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "phase_started";
            phase: components["schemas"]["DebatePhase"];
            /**
             * Round
             * @default 0
             */
            round: number;
        };
        /**
         * ResearchReport
         * @description 1 回の捜査の結果。JSON 保存の単位。
         */
        ResearchReport: {
            /** Topic */
            topic: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Queries */
            queries: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Skipped */
            skipped: components["schemas"]["SkippedSource"][];
        };
        /** RoleAssignment */
        RoleAssignment: {
            /** Role */
            role: string;
            /** Model Key */
            model_key: string;
            /** Model */
            model: string;
            /** Reasoning */
            reasoning: string | null;
            /** Provider */
            provider: string;
            /** Base Url */
            base_url: string;
            /** Json Schema */
            json_schema: boolean;
            /** Json Mode */
            json_mode: boolean;
            /** Streaming */
            streaming: boolean;
            /** Max Concurrency */
            max_concurrency: number;
        };
        /** SessionAborted */
        SessionAborted: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session_aborted";
            /** Reason */
            reason: string;
        };
        /** SessionListItem */
        SessionListItem: {
            /** Session Id */
            session_id: string;
            /** Topic */
            topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_evidence" | "ready" | "in_progress" | "finished" | "aborted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionStarted */
        SessionStarted: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session_started";
            /** Topic */
            topic: string;
            /** Mode */
            mode: string;
            /** Rounds */
            rounds: number;
            /** Models */
            models: {
                [key: string]: string;
            };
            human_side?: components["schemas"]["Side"] | null;
            /**
             * Penalty Gauge
             * @default 0
             */
            penalty_gauge: number;
        };
        /** SessionView */
        SessionView: {
            /** Session Id */
            session_id: string;
            /** Topic */
            topic: string;
            /** Rounds */
            rounds: number;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_evidence" | "ready" | "in_progress" | "finished" | "aborted";
            phase: components["schemas"]["DebatePhase"] | null;
            /** Round */
            round: number;
            next_turn: components["schemas"]["NextTurn"] | null;
            running_task: components["schemas"]["TaskView"] | null;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Statements */
            statements: components["schemas"]["Statement"][];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Citation Issues */
            citation_issues: components["schemas"]["CitationIssue"][];
            /** Judge Scores */
            judge_scores: components["schemas"]["JudgeScore"][];
            verdict: components["schemas"]["Verdict"] | null;
            /** Aborted */
            aborted: string | null;
            human_side: components["schemas"]["Side"] | null;
            /** Penalty Gauge */
            penalty_gauge: number;
            /** Penalty Gauge Max */
            penalty_gauge_max: number;
            pending_choices: components["schemas"]["ChoicesView"] | null;
            /** Choices */
            choices: components["schemas"]["ChoiceOption"][];
        };
        /**
         * Side
         * @enum {string}
         */
        Side: "affirmative" | "negative";
        /**
         * SkippedSource
         * @description 証拠品にしなかった情報源と理由。
         */
        SkippedSource: {
            /** Url */
            url: string;
            /** Reason */
            reason: string;
        };
        /**
         * Statement
         * @description 論者の発言。
         */
        Statement: {
            /** Id */
            id: string;
            side: components["schemas"]["Side"];
            phase: components["schemas"]["DebatePhase"];
            /** Round */
            round: number;
            /** Turn */
            turn: number;
            /** Text */
            text: string;
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
        };
        /** StatementMade */
        StatementMade: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "statement_made";
            statement: components["schemas"]["Statement"];
            /** Call Id */
            call_id?: string | null;
        };
        /** TaskAccepted */
        TaskAccepted: {
            /** Session Id */
            session_id: string;
            task: components["schemas"]["TaskView"];
        };
        /** TaskView */
        TaskView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "research" | "advance" | "run" | "choice";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** TurnMetrics */
        TurnMetrics: {
            /** Statement Id */
            statement_id: string;
            side: components["schemas"]["Side"];
            phase: components["schemas"]["DebatePhase"];
            /** Round */
            round: number;
            /** Chars */
            chars: number;
            /** Ttft Ms */
            ttft_ms: number | null;
            /** Total Ms */
            total_ms: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Tokens Per S */
            tokens_per_s: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            winner: components["schemas"]["Side"] | null;
            /** Agreed */
            agreed: boolean;
            /** Totals */
            totals: {
                [key: string]: number;
            };
            /** Rationale */
            rationale: string;
            /**
             * Decided By
             * @default judge
             * @enum {string}
             */
            decided_by: "judge" | "penalty";
        };
        /** VerdictDelivered */
        VerdictDelivered: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Role */
            role?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "verdict_delivered";
            verdict: components["schemas"]["Verdict"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listEvidenceSamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSample"][];
                };
            };
        };
    };
    useEvidenceSample: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    startResearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advanceSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getChoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoicesView"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chooseOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 選択肢がない */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["SessionStarted"] | components["schemas"]["EvidenceCollected"] | components["schemas"]["PhaseStarted"] | components["schemas"]["StatementMade"] | components["schemas"]["CitationIssuesDetected"] | components["schemas"]["ClaimsExtracted"] | components["schemas"]["JudgeScored"] | components["schemas"]["VerdictDelivered"] | components["schemas"]["SessionAborted"] | components["schemas"]["ChoicesPrepared"] | components["schemas"]["ChoiceMade"] | components["schemas"]["PenaltyApplied"] | components["schemas"]["LLMCallRecorded"])[];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamSession: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE。event は debate(永続イベント、id=seq)/ turn(発言開始)/ token(発言のチャンク)/ progress / task。判決・中断で終わる */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "text/markdown": unknown;
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebateSummary"];
                };
            };
            /** @description セッションがない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 現在の状態ではその操作をできない */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
